### PR TITLE
#89 Add support for strings being the Principal

### LINKED ISSUE #89: Strings not supported as a Principal object
Attempting to use this when the Principal is a String results in the following error:
```
org.crazycake.shiro.exception.PrincipalInstanceException: class java.lang.String must has getter for field: userId
We need a field to identify this Cache Object in Redis. So you need to defined an id field which you can get unique id to identify this principal. For example, if you use UserInfo as Principal class, the id field maybe userId, userName, email, etc. For example, getUserId(), getUserName(), getEmail(), etc.
Default value is "id", that means your principal object has a method called "getId()"
	at org.crazycake.shiro.RedisCache.getPrincipalIdGetter(RedisCache.java:172)
	at org.crazycake.shiro.RedisCache.getRedisKeyFromPrincipalIdField(RedisCache.java:146)
	at org.crazycake.shiro.RedisCache.getStringRedisKey(RedisCache.java:136)
	at org.crazycake.shiro.RedisCache.getRedisCacheKey(RedisCache.java:128)
	at org.crazycake.shiro.RedisCache.put(RedisCache.java:97)
	at org.crazycake.shiro.RedisCacheTest.testPutString(RedisCacheTest.java:110)
[redacted]
```

If the Principal is a string, we have no way to have this module work since there is no getter fields.

Since all we care about is to be able to get a serializable key, we should skip the reflection method invocation and use the Principal as a String as the key.

### PR DESCRIPTION
**Pull request by theo**
Fixes #89 
* Added support for string being the Principal
* Added test case for String support

### CODE REVIEW

**Comment by theo** [comment]
@alexxiyang Please let me know if you have any issues with supporting this or the specific implementation.

Thanks for the project!

**Comment by alexxiyang** [comment]
Looks great!

**Comment by theo** [comment]
Thanks @alexxiyang  - any thoughts on when we can get a release of the latest that includes this patch?

**Comment by alexxiyang** [comment]
I'm thinking about publishing a new release next weekend. I will let you know if new release been published

**Comment by alexxiyang** [comment]
Hi Theodore,

3.2.2 has released

Theodore Nguyen-Cao <notifications@github.com> 于2019年2月28日周四 上午6:52写道：

**Comment by theo** [comment]
Thanks @alexxiyang. It seems like 3.2.2 doesn't include this fix.

https://github.com/alexxiyang/shiro-redis/releases/tag/3.2.2 shows 3.2.2 was released months ago prior to this merged PR.

Am I looking at the right version?

**Comment by alexxiyang** [comment]
Gosh that might be wrong I will release a new version. 3.2.3 today

**Comment by alexxiyang** [comment]
3.2.3 has released. But you might need to wait for 1-2 days since maven
repo needs sometime to refresh the cache

Theodore Nguyen-Cao <notifications@github.com> 于2019年3月18日周一 下午12:54写道：

**Comment by alexxiyang** [comment]
3.2.3 is avaliable now

Xi Yang <alex.xi.yang@gmail.com> 于2019年3月19日周二 上午1:59写道：

**Pull request merged**
