### PR TITLE
Sentinel support

### PR DESCRIPTION
**Pull request by quietcat**

### CODE REVIEW

**Comment by vaamyob** [comment]
Any chance the build errors can be fixed, and the merge request brought in?  I looked in the logs, and didn't actually see any errors.

@quietcat

**Comment by vaamyob** [comment]
Ah, I see now that the error is that the build timed out.

**Comment by alexxiyang** [comment]
Yeah, I agree, the junit is not a good junit. I will add some mocks later

**Comment by murilobandrade** [comment]
Any update?

**Comment by quietcat** [comment]
The test is really an integration test - hard to test as a unit. Probably can be just deleted altogether.

**Comment by alexxiyang** [comment]
Thanks for your pull request. Since the code was refactored, so your pull request cannot be merged to master. But I already copy the code of your branch to master manually.

**Pull request closed without merging**
